{
"issues":  [
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\ActorDslSpec.cs",
"region":  {
"startLine":  131,
"startColumn":  53,
"endLine":  131,
"endColumn":  86
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\ActorLifeCycleSpec.cs",
"region":  {
"startLine":  197,
"startColumn":  23,
"endLine":  197,
"endColumn":  46
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\ActorLifeCycleSpec.cs",
"region":  {
"startLine":  248,
"startColumn":  27,
"endLine":  248,
"endColumn":  47
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  54,
"startColumn":  44,
"endLine":  54,
"endColumn":  94
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  56,
"startColumn":  44,
"endLine":  56,
"endColumn":  82
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  65,
"startColumn":  27,
"endLine":  65,
"endColumn":  79
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  78,
"startColumn":  44,
"endLine":  78,
"endColumn":  94
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  80,
"startColumn":  44,
"endLine":  80,
"endColumn":  82
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Cancellation\CancelableTests.cs",
"region":  {
"startLine":  92,
"startColumn":  31,
"endLine":  92,
"endColumn":  83
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\ReceiveActorTests_LifeCycle.cs",
"region":  {
"startLine":  68,
"startColumn":  65,
"endLine":  68,
"endColumn":  88
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\ReceiveActorTests_LifeCycle.cs",
"region":  {
"startLine":  76,
"startColumn":  65,
"endLine":  76,
"endColumn":  88
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Scheduler\TaskBasedScheduler_ActionScheduler_Schedule_Tests.cs",
"region":  {
"startLine":  203,
"startColumn":  107,
"endLine":  203,
"endColumn":  129
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Stash\ActorWithStashSpec.cs",
"region":  {
"startLine":  249,
"startColumn":  47,
"endLine":  249,
"endColumn":  82
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\Stash\ActorWithStashSpec.cs",
"region":  {
"startLine":  274,
"startColumn":  47,
"endLine":  274,
"endColumn":  82
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Actor\SupervisorHierarchySpec.cs",
"region":  {
"startLine":  58,
"startColumn":  46,
"endLine":  58,
"endColumn":  71
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Dispatch\AsyncAwaitSpec.cs",
"region":  {
"startLine":  203,
"startColumn":  19,
"endLine":  203,
"endColumn":  67
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Dispatch\AsyncAwaitSpec.cs",
"region":  {
"startLine":  235,
"startColumn":  47,
"endLine":  235,
"endColumn":  67
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Dispatch\AsyncAwaitSpec.cs",
"region":  {
"startLine":  381,
"startColumn":  35,
"endLine":  381,
"endColumn":  70
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\Dispatch\AsyncAwaitSpec.cs",
"region":  {
"startLine":  424,
"startColumn":  23,
"endLine":  424,
"endColumn":  43
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\IO\UdpConnectedIntegrationSpec.cs",
"region":  {
"startLine":  70,
"startColumn":  23,
"endLine":  70,
"endColumn":  38
}
}
},
{
"id":  "S112",
"message":  "'System.Exception' should not be thrown by user code.",
"location":  {
"uri":  "sources\akka.net\src\core\Akka.Tests\IO\UdpConnectedIntegrationSpec.cs",
"region":  {
"startLine":  97,
"startColumn":  23,
"endLine":  97,
"endColumn":  38
}
}
}
]
}
